export enum WindowType {
  LOGIN = 'LOGIN',
  MAIN = 'MAIN',
  DIALOG = 'DIALOG',
  SEARCH_ADD = 'SEARCH_ADD',
  USER_DETAIL = 'USER_DETAIL',
  FRIEND_APPLY = 'FRIEND_APPLY',
  IMAGE_EDITOR = 'IMAGE_EDITOR',
  GROUP_FILES = 'GROUP_FILES',
}
